version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.webapp.address=:4000"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=rajkiran616@gmail.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "4000:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - web

  webapp:
    build: 
      context: ./webapp/
    labels:
      - "traefik.http.middlewares.myredirect.redirectscheme.scheme=https"
      - "traefik.http.routes.webapp.middlewares=myredirect"
      - "traefik.http.routes.webapp.rule=Host(`webapptest616.com`,`www.webapptest616.com`)"
      - "traefik.http.routes.webapp.entrypoints=web"
      - "traefik.http.routes.webapp.secure.rule=Host(`webapptest616.com`,`www.webapptest616.com`)"    
      - "traefik.http.routes.webapp.secure.entrypoints=websecure"
      - "traefik.http.routes.webapp.secure.tls.resolver=myhttpchallenge"
      - "traefik.http.routes.webapp.secure.tls=true"      
    ports:
      - 8081:80
    networks:
      - web
networks:
  web:
